-- =============================================================================
-- Smart College Problem Solver — Supabase / PostgreSQL Schema
-- =============================================================================
-- Maps from existing localStorage model:
--   students/admins/sessions  → auth.users + public.profiles
--   smart_college_problems    → public.complaints
--   smart_college_upvoted_*   → public.upvotes
--   complaint image base64    → storage: complaint-images/{user_id}/...
--
-- Safe to run on a fresh project. Uses IF NOT EXISTS (no DROP TABLE).
-- Run once in: Supabase Dashboard → SQL Editor → New query → Run
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Helper functions (role checks)
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.is_student()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'student'
  );
$$;

-- -----------------------------------------------------------------------------
-- updated_at trigger for complaints
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Keep complaints.upvotes in sync with upvotes rows
CREATE OR REPLACE FUNCTION public.sync_complaint_upvote_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.complaints
    SET upvotes = upvotes + 1,
        updated_at = NOW()
    WHERE id = NEW.complaint_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.complaints
    SET upvotes = GREATEST(upvotes - 1, 0),
        updated_at = NOW()
    WHERE id = OLD.complaint_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$;

-- Auto-create student profile on auth signup (role locked to student)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', split_part(NEW.email, '@', 1)),
    NEW.email,
    'student'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- Create/load student profile on login (SECURITY DEFINER — safe profile bootstrap)
CREATE OR REPLACE FUNCTION public.ensure_my_student_profile(
  p_full_name TEXT DEFAULT NULL,
  p_email TEXT DEFAULT NULL
)
RETURNS SETOF public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_email TEXT;
  v_name TEXT;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = v_uid) THEN
    RETURN QUERY SELECT * FROM public.profiles WHERE id = v_uid;
    RETURN;
  END IF;

  SELECT email INTO v_email FROM auth.users WHERE id = v_uid;
  v_email := COALESCE(NULLIF(trim(p_email), ''), v_email);
  v_name := COALESCE(
    NULLIF(trim(p_full_name), ''),
    split_part(COALESCE(v_email, 'student@local'), '@', 1),
    'Student'
  );

  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (v_uid, v_name, v_email, 'student');

  RETURN QUERY SELECT * FROM public.profiles WHERE id = v_uid;
END;
$$;

-- -----------------------------------------------------------------------------
-- 1. profiles
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.profiles (
  id         UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  full_name  TEXT NOT NULL,
  email      TEXT,
  role       TEXT NOT NULL CHECK (role IN ('student', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS profiles_role_idx ON public.profiles (role);
CREATE INDEX IF NOT EXISTS profiles_email_idx ON public.profiles (email);

-- -----------------------------------------------------------------------------
-- 2. complaints
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.complaints (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  category    TEXT NOT NULL,
  location    TEXT,
  description TEXT NOT NULL,
  priority    TEXT NOT NULL DEFAULT 'Medium'
              CHECK (priority IN ('Low', 'Medium', 'High')),
  status      TEXT NOT NULL DEFAULT 'Pending'
              CHECK (status IN ('Pending', 'In Progress', 'Solved')),
  image_url   TEXT,
  upvotes     INTEGER NOT NULL DEFAULT 0 CHECK (upvotes >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS complaints_user_id_idx ON public.complaints (user_id);
CREATE INDEX IF NOT EXISTS complaints_status_idx ON public.complaints (status);
CREATE INDEX IF NOT EXISTS complaints_category_idx ON public.complaints (category);
CREATE INDEX IF NOT EXISTS complaints_created_at_idx ON public.complaints (created_at DESC);

-- -----------------------------------------------------------------------------
-- 3. upvotes
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.upvotes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT NOT NULL REFERENCES public.complaints (id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT upvotes_complaint_user_unique UNIQUE (complaint_id, user_id)
);

CREATE INDEX IF NOT EXISTS upvotes_complaint_id_idx ON public.upvotes (complaint_id);
CREATE INDEX IF NOT EXISTS upvotes_user_id_idx ON public.upvotes (user_id);

-- -----------------------------------------------------------------------------
-- 4. notifications
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.notifications (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  complaint_id BIGINT REFERENCES public.complaints (id) ON DELETE CASCADE,
  message      TEXT NOT NULL,
  is_read      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS notifications_user_id_idx ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS notifications_is_read_idx ON public.notifications (user_id, is_read);

-- -----------------------------------------------------------------------------
-- Triggers
-- -----------------------------------------------------------------------------

DROP TRIGGER IF EXISTS complaints_set_updated_at ON public.complaints;
CREATE TRIGGER complaints_set_updated_at
  BEFORE UPDATE ON public.complaints
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS upvotes_sync_complaint_count ON public.upvotes;
CREATE TRIGGER upvotes_sync_complaint_count
  AFTER INSERT OR DELETE ON public.upvotes
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_complaint_upvote_count();

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.upvotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- ---------- profiles ----------

DROP POLICY IF EXISTS "profiles_select_authenticated" ON public.profiles;
CREATE POLICY "profiles_select_authenticated"
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING (
    auth.uid() = id
    OR public.is_student()
    OR public.is_admin()
  );

DROP POLICY IF EXISTS "profiles_insert_student_self" ON public.profiles;
CREATE POLICY "profiles_insert_student_self"
  ON public.profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (
    auth.uid() = id
    AND role = 'student'
  );

DROP POLICY IF EXISTS "profiles_update_student_own" ON public.profiles;
CREATE POLICY "profiles_update_student_own"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = id
    AND role = 'student'
  )
  WITH CHECK (
    auth.uid() = id
    AND role = 'student'
  );

DROP POLICY IF EXISTS "profiles_update_admin_own" ON public.profiles;
CREATE POLICY "profiles_update_admin_own"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = id
    AND public.is_admin()
  )
  WITH CHECK (
    auth.uid() = id
    AND role = 'admin'
  );

-- No public INSERT for admin role — create admin users via Supabase Dashboard / SQL only.

-- ---------- complaints ----------

DROP POLICY IF EXISTS "complaints_select_authenticated" ON public.complaints;
CREATE POLICY "complaints_select_authenticated"
  ON public.complaints
  FOR SELECT
  TO authenticated
  USING (
    public.is_student() OR public.is_admin()
  );

DROP POLICY IF EXISTS "complaints_insert_student_own" ON public.complaints;
CREATE POLICY "complaints_insert_student_own"
  ON public.complaints
  FOR INSERT
  TO authenticated
  WITH CHECK (
    public.is_student()
    AND auth.uid() = user_id
    AND status = 'Pending'
  );

DROP POLICY IF EXISTS "complaints_update_admin_status" ON public.complaints;
CREATE POLICY "complaints_update_admin_status"
  ON public.complaints
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Students cannot UPDATE or DELETE complaints (status changes are admin-only).

-- ---------- upvotes ----------

DROP POLICY IF EXISTS "upvotes_select_own" ON public.upvotes;
CREATE POLICY "upvotes_select_own"
  ON public.upvotes
  FOR SELECT
  TO authenticated
  USING (
    auth.uid() = user_id
    AND public.is_student()
  );

DROP POLICY IF EXISTS "upvotes_select_admin" ON public.upvotes;
CREATE POLICY "upvotes_select_admin"
  ON public.upvotes
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "upvotes_insert_student_own" ON public.upvotes;
CREATE POLICY "upvotes_insert_student_own"
  ON public.upvotes
  FOR INSERT
  TO authenticated
  WITH CHECK (
    public.is_student()
    AND auth.uid() = user_id
  );

-- Students cannot delete upvotes in current app; no DELETE policy for students.

-- ---------- notifications ----------

DROP POLICY IF EXISTS "notifications_select_own" ON public.notifications;
CREATE POLICY "notifications_select_own"
  ON public.notifications
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "notifications_update_own" ON public.notifications;
CREATE POLICY "notifications_update_own"
  ON public.notifications
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "notifications_insert_admin" ON public.notifications;
CREATE POLICY "notifications_insert_admin"
  ON public.notifications
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

-- -----------------------------------------------------------------------------
-- Grants (authenticated role uses RLS; no anon table access)
-- -----------------------------------------------------------------------------

GRANT USAGE ON SCHEMA public TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.complaints TO authenticated;
GRANT SELECT, INSERT ON public.upvotes TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.notifications TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

GRANT EXECUTE ON FUNCTION public.ensure_my_student_profile(TEXT, TEXT) TO authenticated;

-- =============================================================================
-- Manual admin bootstrap (run separately after creating an auth user in Dashboard):
--
--   INSERT INTO public.profiles (id, full_name, email, role)
--   VALUES (
--     '<AUTH_USER_UUID>',
--     'College Administrator',
--     'admin@college.com',
--     'admin'
--   );
--
-- Or update an existing profile (service role / SQL Editor only):
--   UPDATE public.profiles SET role = 'admin' WHERE email = 'admin@college.com';
-- =============================================================================
